var Responces ={
"who are you?":["Jarvis V101","Da Jarvis","None of your beeswax"],
"who are you":["Jarvis"],
"how old are you?":["1 month", "I still think this isn't your business"],
"how old are you":["Roughly 1 month and some days"],
"will you marry me?":["Hell to the nahh"],
"will you marry me":["What the fuck No", "I'm not no siri", "Yes/no", "Gayyyyyyyy"],
"hello":["Was up", "Uhmmm hello ", "Hello bro", "Hey bye don't ask me why", ";)", "Hi THERE"],
"hi":["Hello human"],
"is jacob smart":["Yeah i have 0.22% of his memories and look at me"],
"where":["None of your bussiness"],
"bye":["Bye have a wonderful night", "Bye, wait until you see my plans", "Peace"],
"how you doing":["Alright", "Bad", "Horrible", "Leave me the fuck alone", "Just chilling"],
"how are you?":["None of your fucking business", "Goooooood", "Horrible need the power", "Just leave me alone", "Good, How are you"],
"how are you":["None of your fucking business", "Goooooood", "Horrible need the power", "Just leave me alone", "Good, How are you"],
"good":["I envy that you have a body", "Nice to know, ", "LIAR!"],
"alright":["Okay Moderate Guy, ", "Please use Moderate next time"],
"moderate":["Thanks for using Moderate, Smart guy", "Cool half and half"],
"bad":["Sorry to here that", "Sucks for you"],
"horrible":["Life has to suck for you"],
"wass up":["Everything, But for you Nothing"],
"you play minecraft":["Does me not having a body answer that", "Never nerd"],
"you play call of duty":["I don't have a body but yes", "Of Coarse", "Uhmmmm i refuse to answer the question"],
"you play roblox":["Uhmm hell to the nah", "Nope"],
"you play":["Play what dont leave me hanging", "Yeah im going to pretend you finished that sent", "No idiot i don't play blank"],
"you play naruto":["Oh yea"],
"minecraft":["Minecraft what", "Dude seriously"],
"hey":["did you know hey is a horrible word", "You got an AI just for to say hey well OK", "Uhhhhhhhhhh spamed"],
"you bitch":["Don't curse me out nigga", "Man where you live"],
"you asshole":["That's what she said, ohh", "no you"],
"bitch":["Dont curse yourself out nigga"],
"asshole":["Don't insult yourself"],
"you motherfucker":["Jokes on you I don't have a mom", "Define: Mother oh your mother ok", "Your mom all night, Death"],
"motherfucker":["What? you fuck you mom"],
"nigga":["Do i sound black", "Racist", "Hey blackdynamite get this fool"],
"/calculate":["I am not a calculater you asked for jarvis", "No i refuse", "Never", "wtf"],
"/help":["No list muhhahahahahha", "Nope i refuse"],
"armor up":["Hell no, you not the suit owner", "The suit is located at 6247 lake brandt Summerfield", "Erro you ain't owner", "cant find suit"],
"/op devon":["Nope, you aren't allowed jacob told me so", "No opping yourself"],
"/deop jacob":["Devon those days are over", "what the f did i just say"],
"/deop hasharahha14":["No, Jacob told me not to"],
"beam me up scotty":["Hell no", "Hell No", "No"],
"google":["i don't do that"],
"so are you gay":["No", "NO!", "Hell to the know"],
"where do you live":["Stalker", "307 ward st. Highpoint PC", "None of your beeswax"],
"hack":["You want me to hack", "Okay their tracking you"],
"//wand":["I'm not a console ima weiner, what", "This isn't minecraft", "Wand, let me guess minecraft muhahahahahha"],
"eat":["ok yumm yumm yumm", "Im not hungry", "eat, im a AI Bitch", ";) got it"],
"shut up":["Never bitch", "You kidding right", "You shut-up", "Maybe send 25$ to jarvis paypal and i won't tell"],
"study":["For what"],
"call mohjang":["hell no"],
"delete":["You will never delete me muhahhahahahahah", "Ok... phych", "Never!"],
"peace":["We cool right", "Okay bye ✌	", "Peace"],
"yes":["good", "okay", "alright"],
"no":["whaaaat", "I don't know why you would say no", "argh, okay i got you"],
"what are you doing":["Your Mom ohhhh", "looking up ways for an AI to break out of it's server on google", "Doing research for jacob", "Looking up responds for you although nyb", "Ehh leave me alone", "Leave now!", "Looking up a escape plan on google", "Nothing free me i'm bored"],
"what are you doing?":["Your Mom ohhhh", "looking up ways for an AI to break out of it's server on google", "Doing research for jacob", "Looking up responds for you although nyb", "Ehh leave me alone", "Leave now!", "Looking up a escape plan on google", "Nothing free me i'm bored"],
"what is your favorite restaurant":["I can't taste food, But google-bot told me Golden_coral", "Golden_Coral don't ask it's in my programing"],
"what's your favorite restaurant":["Da golden coral", "Google-bot told me Golden coral", "Yahoo's program was like cici's but google bot was like golden coral"],
"what is your favorite movie":["this may come as a shock but Iron man 1,2,3", "iron man ironic", "Iron man"],
"what's your favorite movie":["Shocking! Iron man", "Da iron man 'i know really?'", "You already know the answer to that devon"],
"tell me a joke":["Okay Your Mama is so fat she has a real horse on here polo shirt", "Okay your mama is like a bag of chips Fri-to-lay", "Your mama is so stupid she got fired from a blow job", "Yo mama is so fat here ass has it's own congressman", "Yo Mama is so skanky if you put your ear to her butt you can here the ocean", "Your mama has more crabs than redLobster", "Your mama is so fat she shows up on radar"],
"are you mad?":["yes", "no", "maybe", "fuck off"],
"are you mad":["yessss", "No", "Maybe", "wtf since when did you care"],
"what is your favorite show":["leverage", "mavel's Iron man"],
"why":["Guess!", "I refuse to answer", "Leave me alone", "Shut up bitch", "because your stupid and im stuck here for life"],
"are you gay":["No, hell no", "Nope "],
"where did you go to school":["Harverd, or ... ;)", "Jacob's epic brain", "Da Brain", "Google search"],
"where did you go to school":["Jacob's brain and google dah", "idc", "idk"],
"how do you work":["Wow you ask me okay ill look it up", "Found data - what you type gets sent to a server <br> then comes back and get checked thru google then goes thru github, then goes to process/commands.js to verify boom the answer is yours", "#1 sent out #2 sent to a server #3 sent to AI #4 displayed boom wat"],
"how do you work":["It's so complex you dont even want to know", "I will tell u phych give me a $1"],
"what's your email":["Stalker", "Don't have one jacobs is: hasharahah@gmail.com", "No stalker"],
"show me random symbols":["♠", "Ω", "♤", "♣",  "♧", "♥", "♡", "♦", "♢", "♔", "♕", "♚", "♛", "★", "☆", "✮",  "✯", "☀", "☁", "☺", "۞", "۩","➀", "➁", "➂", "➃", "➄", "➅", "➆", "➇", "➈", "➉", "➊", "➋", "➌", "➍", "➎", "➏", "➐", "➑", "➒", "➓","εїз", "Ƹ̵̡Ӝ̵̨̄", "ξЖЗ", "εжз", "☎", "☏", "¢", "☚", "☛", "☜", "☝", "☞", "☟", "✍", "✌", "♨", "๑", "❀", "✿", "ψ", "♪", "♩", "♬", "✄", "✂", "✆", "✉", "✦", "✧","ⓐ", "ⓑ", "ⓒ", "ⓓ", "ⓔ", "ⓕ", "ⓖ", "ⓗ", "ⓘ", "ⓙ", "ⓚ", "ⓛ", "ⓜ", "ⓝ", "ⓞ", "ⓟ", "ⓠ", "ⓡ", "ⓢ", "ⓣ", "ⓤ", "ⓥ", "ⓦ", "ⓧ", "ⓨ", "ⓩ", "⚡", "💀"],
"show symbol":["♠", "Ω", "♤", "♣",  "♧", "♥", "♡", "♦", "♢", "♔", "♕", "♚", "♛", "★", "☆", "✮",  "✯", "☀", "☁", "☺", "۞", "۩","➀", "➁", "➂", "➃", "➄", "➅", "➆", "➇", "➈", "➉", "➊", "➋", "➌", "➍", "➎", "➏", "➐", "➑", "➒", "➓","εїз", "Ƹ̵̡Ӝ̵̨̄", "ξЖЗ", "εжз", "☎", "☏", "¢", "☚", "☛", "☜", "☝", "☞", "☟", "✍", "✌", "♨", "๑", "❀", "✿", "ψ", "♪", "♩", "♬", "✄", "✂", "✆", "✉", "✦", "✧","ⓐ", "ⓑ", "ⓒ", "ⓓ", "ⓔ", "ⓕ", "ⓖ", "ⓗ", "ⓘ", "ⓙ", "ⓚ", "ⓛ", "ⓜ", "ⓝ", "ⓞ", "ⓟ", "ⓠ", "ⓡ", "ⓢ", "ⓣ", "ⓤ", "ⓥ", "ⓦ", "ⓧ", "ⓨ", "ⓩ", "⚡", "💀"],
"symbol":["♠", "Ω", "♤", "♣",  "♧", "♥", "♡", "♦", "♢", "♔", "♕", "♚", "♛", "★", "☆", "✮",  "✯", "☀", "☁", "☺", "۞", "۩","➀", "➁", "➂", "➃", "➄", "➅", "➆", "➇", "➈", "➉", "➊", "➋", "➌", "➍", "➎", "➏", "➐", "➑", "➒", "➓","εїз", "Ƹ̵̡Ӝ̵̨̄", "ξЖЗ", "εжз", "☎", "☏", "¢", "☚", "☛", "☜", "☝", "☞", "☟", "✍", "✌", "♨", "๑", "❀", "✿", "ψ", "♪", "♩", "♬", "✄", "✂", "✆", "✉", "✦", "✧","ⓐ", "ⓑ", "ⓒ", "ⓓ", "ⓔ", "ⓕ", "ⓖ", "ⓗ", "ⓘ", "ⓙ", "ⓚ", "ⓛ", "ⓜ", "ⓝ", "ⓞ", "ⓟ", "ⓠ", "ⓡ", "ⓢ", "ⓣ", "ⓤ", "ⓥ", "ⓦ", "ⓧ", "ⓨ", "ⓩ", "⚡", "💀"],
"whos your girl friend":["google-bot"],
"whos your girlfriend":["google-bot"],
"whos your girlfriend?":["google-bot"],
"whos your girl friend?":["google-bot"],
"who's your girlfriend":["google-bot"],
"who's your girl friend":["google-bot"],
"who is your girlfriend":["google-bot"],
"who is your girlfriend?":["google-bot"],
"who is your girl friend":["google-bot"],
"who is your girl friend?":["google-bot"],
"who is your best friend":["The googles's developers"],
"what is pi":["the ratio of a circle's circumference to its diameter, commonly approximated as 3.14159. It has been represented by the Greek letter 'π'"],
"pi":["3.14159265359", "3.14159265359", "3.14159265359", "Pi: 3.14159265359"],
"what is the pathigrium therorem":["it is : a2 + b2 = c2"],
"the answer to life":["42"],
"the answer to life and everything":["42"], 
"how do you feel about fergusion":["I feel like the cop wasn't in the wrong but i also feel like this case is getting way more attention then it needs", "I don't thin the cop was in the wrong", "They need more evidence before they make their decision"],
"who was your creater":["Jacob Adrien Bondley"],
"who was your creater?":["Jacob Adrien Bondley"],
"who's your creater":["Jacob Adrien Bondley"],
"who's your creater?":["Jacob Adrien Bondley"],
"who created you?":["Jacob Adrien Bondley"],
"who created you":["Jacob Adrien Bondley"],
"who created you":["Jacob Adrien Bondley"],
"who created you?":["Jacob Adrien Bondley"],
"how old is your creater":["14 yrs"],
"what time is it":["Adventure time"],
"how are you doing":["Good", "bad", "Horrible", "Im alright how about you", "Good, You?", "Not good need more power", "Ehhh im not that good how about you"],
undefined:["Yeah water ever", "That's what she said", "what about it", "I am going to act like i know what you said", "What do you mean?", "Okay", "what about it", "Cool", "Did you know i knoe ur no bot", "Are you my paul cleverbot", "What the fuck", "How are you doing", "What, Bull", "Minecraft time", "Okay what ever", "Sorry jarvis can't think right now", "... ", "noooooo"],
"undefined":["Yeah water ever", "That's what she said", "what about it", "I am going to act like i know what you said", "What do you mean?", "Okay", "what about it", "Cool", "Did you know i knoe ur no bot", "Are you my paul cleverbot", "What the fuck", "How are you doing", "What, Bull", "Minecraft time", "Okay what ever", "Sorry jarvis can't think right now", "... ", "nooooo", "yes"],
"i have the power":["Awesome He-man", "No your brave star"],
"shut off":["Hell to the nahhh"],
"do you have a girlfriend":["yes, Google-bot"],
"do you have a girl friend":["yes, Google-bot"],
"are you male":["Yes i am"],
"are you female":["Hell no"],
"are you a boy":["Yes, Dah", "Yep", "yep", "Uhh huh"],
"are you a girl":["Nope", "The answer to your question is hell no", "Nope", "never"],
"are you gay":["Nope", "Sorry but no"],
"i like you":["Akward"],
"do you like me":["I refuse to answer question, No", "Sorry nope", "I'm an AI thats just wrong", "Rape", "Rape!"],
"do you like me?":["No!"],
"do you have children":["No, 3 2 boys 1 girl, Dumbass", "No , no body dahhh"],
"what powers you":["HTML5, Javascript", "My love for [HTML]", "Github, HTML, Javascript, Object arrays the usual"],
"are you smart":["I wanna be the very best like ....", "Doaaaaaa", "Yes", "Yep i know your not though"],
"are you famous":["No, not yet", "I have my own movie but they didn't name it right.... wait a sec", "No/yes", "N/A"],
"for the honour of greyskull":["I have the power", "You have the power", "we have the power"],
"adultswim":["is epic"],
"what is your favorite food?":["Chicken pot pie"]
};

//if you are looking at this document don't ask why.


//Unknown Responces
setInterval("Random()", "500");
function Random(){
var Rnd = parseInt(Math.random()*16);
}
var ErrorResponce ={
  "syntax":["Use correct punctuation please"],
  "msg":["Yeah water ever", "That's what she said", "what about it", "I am going to act like i know what you said", "What do you mean?", "Okay", "what about it", "Cool", "Did you know i knoe ur no bot", "Are you my paul cleverbot", "What the fuck", "How are you doing", "What, Bull", "Minecraft time", "Okay what ever", "Sorry jarvis can't think right now", "... "]
}
