var Responces ={
"who are you?":["Jarvis V100","Da Jarvis","None of your beeswax"],
"who are you":["Jarvis"],
"how old are you?":["1 month", "I still think this isn't your business"],
"how old are you":["Roughly 1 month and some days"],
"will you marry me?":["Hell to the nahh"],
"will you marry me":["What the fuck No", "I'm not no siri", "Yes/no", "Gayyyyyyyy"],
"hello":["Was up", "Uhmmm hello ", "Hello bro"],
"bye":["Bye have a wonderful night", "Bye, wait until you see my plans", "Peace"],
"how you doing":["Alright", "Bad", "Horrible", "Leave me the fuck alone", "Just chilling"],
"how are you?":["None of your fucking business", "Goooooood", "Horrible need the power", "Just leave me alone", "Good, How are you"],
"good":["I envy that you have a body", "Nice to know, ", "LIAR!"],
"alright":["Okay Moderate Guy, ", "Please use Moderate next time"],
"moderate":["Thanks for using Moderate, Smart guy", "Cool half and half"],
"bad":["Sorry to here that", "Sucks for you"],
"horrible":["Life has to suck for you"],
"wass up":["Everything, But for you Nothing"],
"you play minecraft":["Does me not having a body answer that", "Never nerd"],
"you play call of duty":["I don't have a body but yes", "Of Coarse", "Uhmmmm i refuse to answer the question"],
"you play roblox":["Uhmm hell to the nah", "Nope"],
"you play":["Play what dont leave me hanging", "Yeah im going to pretend you finished that sent", "No idiot i don't play blank"],
"you play naruto":["Oh yea"],
"minecraft":["Minecraft what", "Dude seriously"],
"hey":["did you know hey is a horrible word", "You got an AI just for to say hey well OK", "Uhhhhhhhhhh spamed"],
"you bitch":["Don't curse me out nigga", "Man where you live"],
"you asshole":["That's what she said, ohh", "no you"],
"bitch":["Dont curse yourself out nigga"],
"asshole":["Don't insult yourself"],
"you motherfucker":["Jokes on you I don't have a mom", "Define: Mother oh your mother ok", "Your mom all night, Death"],
"motherfucker":["What? you fuck you mom"],
"nigga":["Do i sound black", "Racist", "Hey blackdynamite get this fool"],
"/calculate":["I am not a calculater you asked for jarvis", "No i refuse", "Never", "wtf"],
"/help":["No list muhhahahahahha", "Nope i refuse"],
"armor up":["Hell no, you not the suit owner", "The suit is located at 6247 lake brandt Summerfield", "Erro you ain't owner", "cant find suit"],
"/op devon":["Nope, you aren't allowed jacob told me so", "No opping yourself"],
"/deop jacob":["Devon those days are over", "what the f did i just say"],
"/deop hasharahha14":["No, Jacob told me not to"],
"beam me up scotty":["Hell no", "Hell No", "No"],
"google":["i don't do that"]
};
